### ISSUE TITLE
Unused type

### ISSUE THREAD

**Issue by DanielSank** [bemeurer/hemoglobin#9]
[Here](https://github.com/bemeurer/hemoglobin/blob/87b105cfd779acdf3eff574bc774e9be6d9779e1/src/main.rs#L21)

```rust
impl std::ops::Add<Cell> for Cell {
    type Output = Cell;
    fn add(self, rhs: Cell) -> Cell {
        if self.is_zero() && rhs.is_zero() {
            Cell::Dead
        } else {
            Cell::Alive
        }
    }
}
```

What is `type Output = Cell;` for?

**Comment by lovesegfault** [comment]
That's not unused, it's necessary to specify who gets to pick the output type. You can read more about it on [StackOverflow](https://stackoverflow.com/a/39118492/2080712).
